local BASE_ANIMATION_SPEED = 0.32

data:extend({ {
    type = "lab",
    name = "uranium-expanded-nuclear-lab",
    energy_usage = "2000kW",
    researching_speed = 1.5,
    module_slots = 2,
    science_pack_drain_rate_percent = 45,
    energy_source = {
        type = "burner",
        fuel_categories = { "uranium-expanded-uranium-catalyst" },
        burnt_inventory_size = 1,
        fuel_inventory_size = 1,
        effectivity = 0.1,
        render_no_power_icon = false, -- no power icon else it would clash with electricity icon from eei
        light_flicker = {
            minimum_light_size = 1.0,
            color = { 0.3, 1.0, 0.3, 1.0 }
        }
    },
    -- custom_tooltip_fields = { { name = "testname", value = "testvalue" } },
    icon = "__uranium-expanded__/graphics/icons/nuclear-lab-icon.png",
    minable = { mining_time = 0.5, result = "uranium-expanded-nuclear-lab" },
    subgroup = "production-machine",
    inputs = {
        "automation-science-pack",
        "logistic-science-pack",
        "military-science-pack",
        "chemical-science-pack",
        "production-science-pack",
        "utility-science-pack",
        "space-science-pack",
        "metallurgic-science-pack",
        "agricultural-science-pack",
        "electromagnetic-science-pack",
        "cryogenic-science-pack",
        "promethium-science-pack"
    },
    order = "z-z[z-lab]",
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    collision_box = { { -2.2, -2.2 }, { 2.2, 2.2 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    max_health = 350,
    impact_category = "metal",
    icon_draw_specification = { shift = { 0, -0.3 } },
    corpse = "big-remnants",
    dying_explosion = "big-explosion",
    on_animation = {
        layers = {
            {
                animation_speed = BASE_ANIMATION_SPEED,
                scale = 0.4,
                filenames = {
                    "__uranium-expanded__/graphics/entity/nuclear-lab/nuclear-lab-hr-animation-1.png",
                },
                blend_mode = "normal",
                width = 400,
                height = 400,
                line_length = 8,
                lines_per_file = 8,
                frame_count = 60,
                shift = util.by_pixel_hr(0, 0),
                tint = { r = 1, g = 1, b = 1, a = 1 },
            },
            {
                animation_speed = BASE_ANIMATION_SPEED,
                scale = 0.4,
                filenames = {
                    "__uranium-expanded__/graphics/entity/nuclear-lab/nuclear-lab-hr-emission-1.png",
                },
                blend_mode = "additive-soft",
                width = 400,
                height = 400,
                line_length = 8,
                lines_per_file = 8,
                frame_count = 60,
                shift = util.by_pixel_hr(0, 0),
                tint = { r = 1, g = 1, b = 1, a = 1 },
                draw_as_glow = true,
            },
            {
                scale = 0.4,
                filenames = {
                    "__uranium-expanded__/graphics/entity/nuclear-lab/nuclear-lab-hr-shadow.png",
                },
                blend_mode = "normal",
                width = 800,
                height = 600,
                line_length = 1,
                lines_per_file = 1,
                frame_count = 1,
                repeat_count = 60,
                shift = util.by_pixel_hr(0, 0),
                tint = { r = 1, g = 1, b = 1, a = 1 },
                draw_as_shadow = true,
            },
        },
    },
    off_animation = {
        layers = {
            {
                animation_speed = BASE_ANIMATION_SPEED,
                scale = 0.4,
                filenames = {
                    "__uranium-expanded__/graphics/entity/nuclear-lab/nuclear-lab-hr-animation-1.png",
                },
                blend_mode = "normal",
                width = 400,
                height = 400,
                line_length = 8,
                lines_per_file = 8,
                frame_count = 60,
                shift = util.by_pixel_hr(0, 0),
                tint = { r = 1, g = 1, b = 1, a = 1 },
            },
            {
                scale = 0.4,
                filenames = {
                    "__uranium-expanded__/graphics/entity/nuclear-lab/nuclear-lab-hr-shadow.png",
                },
                blend_mode = "normal",
                width = 800,
                height = 600,
                line_length = 1,
                lines_per_file = 1,
                frame_count = 1,
                repeat_count = 60,
                shift = util.by_pixel_hr(0, 0),
                tint = { r = 1, g = 1, b = 1, a = 1 },
                draw_as_shadow = true,
            },
        },
    },
} })
